name: Run Notebook on PR

on:
  pull_request:
    branches:
      - main 
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13' 

      - name: Install Dependencies
        run: |
          pip install matplotlib pandas pathlib numpy nbconvert nbformat papermill

      - name: Execute Notebook
        id: run_notebook
        run: |
          papermill compare_results.ipynb output.ipynb --log-output || echo "Notebook execution failed" > error.log

      - name: Comment on PR if Failed
        if: failure()
        run: |
          echo "Notebook execution failed. Please check compare_results.ipynb." | tee comment.txt
          gh pr comment ${{ github.event.pull_request.number }} --body "$(cat comment.txt)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
